import type { NextPage } from "next";
import Head from "next/head";
import { ViewConfiguration } from "@components/ViewConfiguration";
import { Hero } from "@components/Home/Hero";
import { RoleplayTable } from "@components/Home/RoleplayTable";

const Home: NextPage = () => {
  return (
    <ViewConfiguration>
      <>
        <Head>
          <title>RPG Connect | Encontre mesas para jogar</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Hero />
        <RoleplayTable />
      </>
    </ViewConfiguration>
  );
};

export default Home;
